[project]
name = "ncaa-predictions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "scikit-optimize>=0.10.2",
    "torch>=2.10.0",
    "xgboost>=3.0.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
